### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/pokemon-type-predictor#13]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

**CONTRIBUTING.md**
- [x] Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -1
**Comment:** Core teams contribution workflow is not mentioned

**Exploratory data analysis in a literate code document**
- [x] The document contains some problem. For instance, a plot that is not rendered correctly. -1
**Comment:** Figures are rendered blank. 
- [x]  There figure captions for the tables should be above the table. -1 viz
**Comment:** Table captions missing.
