### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/pokemon-type-predictor#24]
Congratulations, gym leaders, on finishing milestone 2! I think your repo is going to help pokemon trainers around the world hone their skills. I was able to recreate your analysis without any problems. 

- [x] Analysis code is satisfactory.
- [x] Version controlling was satisfactory.
- [x] The project file and directory structure organization look good. 
- [x] Submission expectations were met.

Best of luck with milestone 3.
