### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/pokemon-type-predictor#26]
- [x] In README, document how long script takes to run (in Docker, as well as locally?)
- [x] Create dependency graph using [makefile2graph](https://github.com/lindenb/makefile2graph)
- [x] Create `Dockerfile` (include all the software and libraries/packages to run, but not the repo, this file lives in the repo)
- [x] Use Github Actions to build Docker image from Dockerfile 
- [x] NO data or code in Dockerfile
- [x] Update README for Docker usage (running analysis AND cleaning directories)
- [x] Add comment in [here](https://github.com/UBC-MDS/data-analysis-review-2021/issues) about four pieces of feedback we agree with
- [x] Paste link with each commit of adding the feedback to the project
- [x] Create release (1.0.0) and submit to Canvas!
