### ISSUE TITLE
Milestone 4 feedback reorganized

### ISSUE THREAD

**Issue by carolinetang77** [UBC-MDS/pokemon-type-predictor#29]
Division of tasks listed in #25 :
These are the ones I'm planning on working on, and each person can list what they're doing and edit their own comments as needed:
- [x] Reason for choosing specific models (in report and README) ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/commit/ecdc4122f85a66f043238b34a060a91891000419))
- [x] add more details in the README.md about the features of the data ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/commit/c2f0b8ecf88fa58f9b7190e734a2dbea2bc3534a))
- [x] adding info about hyperparameter tuning in report ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/commit/57812673df068027006ba8745f65efd7edfb9755))
- [x] justify why we chose accuracy as our scoring metric ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/commit/57812673df068027006ba8745f65efd7edfb9755))
- [x] mention that conda is required if not using docker

**Comment by WilfHass** [comment]
@missarah96  is doing (from #25) 
- [x] justify preprocessing steps in report (dropping columns, imputation)
- [x] add links to license, code of conduct
- [x] from #26 , can you add how long the analysis takes to run? both with `make` and `docker`  

I'm doing:
- [x] Updating dependency list ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/commit/c7a2ba8327e99cf1efbc2add5ae27c87cd467449#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5))

@vincentho32  is doing:
- [x] add webpage link of final report in README ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/pull/35/commits/ab065f0eba3314162b5048fb0e57144682f450ba))
- [x]  add EDA plot in Rmd ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/pull/35/commits/79ac70ced62f5879de29380559fbb272b6b35649))
- [x]  add dependency diagram in README.md ([commit link](https://github.com/UBC-MDS/pokemon-type-predictor/pull/35/commits/4e67019b33f89a8e10696152069fc9d777cca635))

Remember to commit after finishing each task so we can paste links to them in the submission!
Similarly, we need to add which comments we agree with and that we are fixing in [here](https://github.com/UBC-MDS/data-analysis-review-2022/issues/5)
